services:
  plannet_front_app:
    build:
      context: .
      dockerfile: plannet_front_app/Dockerfile
    networks:
      - plannet-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/darkt.ru.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    networks:
      - plannet-network
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email ekip-s@yandex.ru --agree-tos --no-eff-email -d darkt.ru -d www.darkt.ru
    depends_on:
      - nginx
    networks:
      - plannet-network  

networks:
  plannet-network:
    driver: bridge

volumes:
  certs:
  certbot_www: