services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - main-network
      - keycloak-main-network

  plannet_front_app:
    build:
      context: .
      dockerfile: plannet_front_app/Dockerfile
    expose:
      - "5173"
    restart: always
    networks:
      - main-network
      - keycloak-main-network

  keycloak-db:
    image: postgres:16.2
    container_name: keycloak_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgresdata:/var/lib/postgresql/data
    restart: always 
    networks: 
      - keycloak-db-network
    
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    container_name: keycloak
    command: ["start"]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      # Аутентификация администратора
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      # Настройки хоста (актуальная версия v2)
      KC_CONTEXT_PATH: /auth
      KC_HOSTNAME_URL: https://darkt.ru  
      KC_HOSTNAME_ADMIN_URL: https://darkt.ru/auth/admin
      # Настройки проксирования
      KC_PROXY: edge 
      KC_PROXY_HEADERS: forwarded
      KC_HTTP_ENABLED: true 
      # Отключаем проверки для работы за прокси
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: "false"
      # Логирование
      KC_LOG_LEVEL: DEBUG
    restart: always 
    networks: 
      - keycloak-db-network  
      - keycloak-main-network

volumes:
  cert_data:
  postgresdata:  

networks:
  main-network:
    driver: bridge
  keycloak-db-network:
    driver: bridge  
  keycloak-main-network:
    driver: bridge  
    internal: false