services:
  plannet_front_app:
    build:
      context: .
      dockerfile: plannet_front_app/Dockerfile
    volumes:
      - ./plannet_front_app:/app
    ports:
      - "80:80"
    networks:
      - front_network

  nginx:
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./darkt.ru.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/ssl
    ports:
      - "80:80"
      - "443:443"
    networks:
      - front_network
    depends_on:
      - plannet_front_app
      - certbot

  certbot:
    image: certbot/certbot
    container_name: certbot_container
    volumes:
      - ./ssl:/etc/ssl
    entrypoint: "/bin/sh -c 'trap exit TERM; certbot certonly --standalone --preferred-challenges http --email your-email@example.com --agree-tos --no-eff-email -d darkt.ru -d www.darkt.ru && while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - front_network
    depends_on:
      - nginx

networks:
  front_network:
    driver: bridge
