services:
  plannet_front_app:
    build:
      context: .
      dockerfile: plannet_front_app/Dockerfile
    volumes:
      - ./plannet_front_app:/app
    ports:
      - "5173:5173"  
    networks:
      - front_network

networks:
  front_network:
    driver: bridge
