version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt  # Bind mount
      - ./certbot/www:/var/www/certbot
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - main-network

  certbot:
    image: certbot/certbot
    volumes:
      - cert_data:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - main-network  

  plannet_front_app:
    build:
      context: .
      dockerfile: plannet_front_app/Dockerfile
    volumes:
      - ./plannet_front_app:/app
    networks:
      - main-network
    expose:
      - "5173"
    restart: always  

volumes: 

networks:
  main-network:
    driver: bridge