services:
  plannet_front_app:
    build:
      context: .
      dockerfile: plannet_front_app/Dockerfile
    networks:
      - plannet-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/darkt.ru.conf:/etc/nginx/darkt.ru.conf
      - ./certs:/etc/letsencrypt
      - ./plannet_front_app/dist:/usr/share/nginx/html
      - ./plannet_front_app/dist/.well-known:/usr/share/nginx/html/.well-known  # добавил это
    depends_on:
      - plannet_front_app
    networks:
      - plannet-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./plannet_front_app/dist:/usr/share/nginx/html
      - ./plannet_front_app/dist/.well-known:/var/www/certbot/.well-known  # изменил путь
    command: certonly --webroot --webroot-path=/var/www/certbot/.well-known --email your@email.com --agree-tos --no-eff-email --force-renewal -d darkt.ru -d www.darkt.ru
    depends_on:
      - nginx

networks:
  plannet-network:
    driver: bridge

volumes:
  certs:
