services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - main-network

  plannet_front_app:
    build:
      context: .
      dockerfile: plannet_front_app/Dockerfile
    expose:
      - "5173"
    restart: always
    networks:
      - main-network

volumes:
  cert_data:

networks:
  main-network:
    driver: bridge      